name: Release
on:
  release:
    branches-ignore:
      - /.*/
    tags:
      - /^v\d+[.]\d+[.]\d+$/
    
jobs:
  draft:
    runs-on: ubuntu-latest
    needs: [node8-latest, node10-latest]
    steps:
    - uses: actions/checkout@master
  check_github_releases:
    name: Check Github Releases!
    needs: draft
    # type: approval
    steps:
    - uses: actions/checkout@master
  publish:
    needs: check_github_releases
    steps:
    - uses: actions/checkout@master
        